### ISSUE TITLE
typo in countryflags.module.js ?

### ISSUE THREAD

**Issue by mavrick** [OscarYuen/angular-countryflags-directive#1]
Hey there,

I am trying to integrate your module into my angular app but when I build with grunt I am getting an error when loading the module ``Uncaught Error: [$injector:nomod] Module 'ng-countryflags' is not available! You either misspelled the module name or forgot to load it.``

If I update countryflags.module.js to

```javascript
angular.module('ng-countryflags', []);
```

I can successfully integrate the module. 

Please let me know if I have misunderstood anything, 

Also, I think an update to your documentation would also be beneficial to help others integrate this module.

Cheers

**Comment by OscarYuen** [comment]
Thanks @mavrick 
Yes, there is a typo on the module file and I updated it. 
For the documentation, I would try to work out more examples on it. Thanks for the suggestion.
